#!/usr/bin/env python
import sys
import os
import os.path

from pyraf import iraf

inputImg = "/Users/xu/Bulgeless/play_data/NGC300/R/NGC300_R_reg_sky.fit"
outTab = inputImg.replace(".fit", "_ellipse_1.tab")
outDat = inputImg.replace(".fit", "_ellipse_1.dat")

iraf.stsdas()
iraf.analysis()
iraf.isophote()

if os.path.exists(outTab):
    os.remove(outTab)
if os.path.exists(outDat):
    os.remove(outDat)

iraf.ellipse(sma0=100,maxsma=1200,interactive=True,x0=1145.76,y0=993.043,input=inputImg,out=outTab,fflag=0.9,hcenter=True,pa = 111-180, e = 0.26, hpa = True, hellip=True)



iraf.tdump(table=outTab, datafile=outDat)
